on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          sudo apt update
          sudo apt install gnat gprbuild
      - run: gprbuild -v -Xmode=debug -j$(nproc) ugbl_tests.gpr
      - run: ./out/ugbl_tests
